# GitLab CI/CD for Browser Extension

stages:
  - build
  - release

variables:
  PACKAGE_NAME: "gitlab-mr-chain-visualizer"
  # Use the tag for the version, e.g., v0.1.0
  PACKAGE_VERSION: $CI_COMMIT_TAG

# This stage builds the extension and creates a zip artifact
build_extension:
  stage: build
  image: node:18 # Using a Node.js version compatible with dependencies
  script:
    - echo "Building extension version $PACKAGE_VERSION..."
    - npm install
    - npm run lint
    - npm run build
    # Install archiver to create a zip file of the build
    - npm install -g archiver
    - cd dist && archiver zip -r "../${PACKAGE_NAME}-${PACKAGE_VERSION}.zip" . && cd ..
    - echo "Build artifact created: ${PACKAGE_NAME}-${PACKAGE_VERSION}.zip"
  artifacts:
    paths:
      - "${PACKAGE_NAME}-${PACKAGE_VERSION}.zip"
  # This job only runs when a tag is pushed
  only:
    - tags

# This stage creates a new release in GitLab
create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Creating release for tag $CI_COMMIT_TAG..."
    - release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
      --description "Release of version $CI_COMMIT_TAG of the GitLab MR Chain Visualizer." \
      --assets-link "{\"name\":\"${PACKAGE_NAME}-${PACKAGE_VERSION}.zip\",\"url\":\"${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_TAG}/raw/${PACKAGE_NAME}-${PACKAGE_VERSION}.zip?job=build_extension\"}"
  # This job only runs when a tag is pushed
  only:
    - tags 