# GitHub Actions CI/CD for Browser Extension

name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v0.1, v1.0.0, etc.

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the extension
        run: npm run build

      - name: Package the extension
        run: |
          cd dist
          zip -r ../gitlab-mr-chain-visualizer-${{ github.ref_name }}.zip .
          cd ..

      - name: Install GitHub CLI
        uses: cli/cli-action@v2

      - name: Create GitHub Release using gh CLI
        run: |
          gh release create "${{ github.ref_name }}" \
            "gitlab-mr-chain-visualizer-${{ github.ref_name }}.zip" \
            --title "Release ${{ github.ref_name }}" \
            --notes "Release of version ${{ github.ref_name }} of the GitLab MR Chain Visualizer."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}